### ISSUE TITLE
add a general prefix

### ISSUE THREAD

**Issue by paulovieira** [vitaly-t/pg-monitor#1]
It would be great if there was an option to add a general prefix to the output. For instance:

``` javascript
var monitor = require("pg-monitor");
monitor.setPrefix("postgres: ");
monitor.attach();
// proceed with the call to pgpLib
```

Instead of

```
15:46:35 connect(clima@150601)
15:46:35 select * from maps_create('[{"id":1,"code":"energia_centrais"}]')
15:46:35 disconnect(clima@150601)
```

the output would be

```
15:46:35 postgres: connect(clima@150601)
15:46:35 postgres: select * from maps_create('[{"id":1,"code":"energia_centrais"}]')
15:46:35 postgres: disconnect(clima@150601)
```

Even better: allow simple customization of the date format:

``` javascript
monitor.setDateFormat("YYMMDD HH:MM:SS");
```

``` javascript
monitor.setDateFormat("HH:MM:SS");
```

etc

**Comment by vitaly-t** [comment]
Your typical screen has limited width of 80 symbols, that's why I kept the repeated details to the minimum. Usually one doesn't need the whole Date/Time to analyse the system in real time, only the Time.

The only place you might want the whole Date/Time + extra details is when logging this information into a file. This is why I implemented a very detailed [log event](https://github.com/vitaly-t/pg-monitor#log), using which you can output everything into your own log file in any format you like, including exactly what you specified there, like your own Date/Time format and a prefix.

``` javascript
monitor.log = function (msg, info) {
    // save messages into your log file in any format you like;
    console.log(info);
};
```

See [log event](https://github.com/vitaly-t/pg-monitor#log).

**Comment by vitaly-t** [comment]
Closing, due to inactivity.
