### ISSUE TITLE
default for white screen

### ISSUE THREAD

**Issue by kshji** [vitaly-t/pg-monitor#4]
None of defaults works in white bg screen. Ex. matrix white => black works fine. I have used over  20 years white bg and black fg. I'm sure I'm not only who has got enough dark bg and green or amber fg.

Of course you can make own theme, but it would be nice if some of defaults is usable also this kind of screens.

**Comment by vitaly-t** [comment]
That sounds like a special case, and a good example where use of a [custom theme](https://github.com/vitaly-t/pg-monitor/wiki/Color-Themes#custom-themes) is appropriate.

See [method setTheme](https://github.com/vitaly-t/pg-monitor#setthemet) and [Color Themes](https://github.com/vitaly-t/pg-monitor/wiki/Color-Themes).

You can easily define your own color theme that will look good on your white background ;)

If you design a theme that looks good on white background - post it here, I can add it to the list ;)

**Comment by vitaly-t** [comment]
@kshji closing, due to inactivity.

**Comment by nonplus** [comment]
FWIW, black-on-white is fairly common on the Mac (that's the default in the terminal app, InteliJ's IDEs, etc.) and `color.whiteBright` is the only real problem.

I'm using the default theme but with `blue` instead of `whiteBright` for the `query` and am pretty happy with it.  It would be nice if something like it were built-in.

```
pgMonitor.setTheme({
	time: color.bgWhite.black,
	value: color.white,
	cn: color.yellow,
	tx: color.cyan,
	paramTitle: color.magenta,
	errorTitle: color.redBright,
	query: color.blue,
	special: color.green,
	error: color.red
});
```

**Comment by vitaly-t** [comment]
@nonplus thanks, I will look into it ;)

**Comment by vitaly-t** [comment]
I took my time to consider this, and I'm not convinced about adding anymore themes, because...

We cannot determine the background color used by the console, so it cannot be automatic.

If you are using a white background color, then you can either set a new theme, which is what you did above, or you can select an existing one, and then tweak just one color you do not like:

```js
var color = require("cli-color");
monitor.setTheme('matrix');
var theme = require('pg-monitor/lib/themes').matrix;
theme.query = color.blue; // override query color in the theme to be blue
```

All the mechanism is there, and it is the minimum effort for anyone to tweak colors or set the entire custom theme is you please.

Therefore, I am closing the issue.

**Comment by ravinggenius** [comment]
Even if the background color cannot be automatically discovered, it would nice to have at least *one* built-in theme that works well with a light background, even if it's just "monochrome-invert".

**Comment by vitaly-t** [comment]
@ravinggenius feel free to do a PR with such a theme.

**Comment by ravinggenius** [comment]
Thanks for re-considering this.

**Comment by vitaly-t** [comment]
New black-on-white theme [invertedMonochrome](https://github.com/vitaly-t/pg-monitor/wiki/Color-Themes#invertedmonochrome) was added in version 0.9.1
